version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_login
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_clase
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"


      # docker compose up -d